name: Tests de integraci贸n TipoPago - DEV-QA

on:
  push:
    branches:
      - DEV-QA
    paths:
      - 'src/components/TipoPago/**'
      - 'tests/integration/tipopago.test.js'
      - '.github/workflows/dev-qa-tipopago.yml'
      - 'package.json'
      - 'yarn.lock'
      - 'package-lock.json'
  pull_request:
    branches:
      - DEV-QA
    paths:
      - 'src/components/TipoPago/**'
      - 'tests/integration/tipopago.test.js'
      - '.github/workflows/dev-qa-tipopago.yml'
      - 'package.json'
      - 'yarn.lock'
      - 'package-lock.json'

jobs:
  test:
    name: Ejecutar pruebas de integraci贸n TipoPago
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Ejecutar pruebas de integraci贸n TipoPago
        run: |
          if [ -f yarn.lock ]; then
            yarn test tests/integration/tipopago.test.js
          else
            npm test -- tests/integration/tipopago.test.js
          fi
