name: Tests de integración - DEV-QA

on:
  push:
    branches:
      - DEV-QA
      - main
  pull_request:
    branches:
      - DEV-QA
      - main

jobs:
  test:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas de TipoPago
        run: npm run test:tipopago

      - name: Ejecutar pruebas de Categoria
        run: npm run test:categoria

      - name: Ejecutar pruebas de Comentario
        run: npm run test:comentario

      - name: Ejecutar pruebas de Registrar
        run: npm run test:registrar

      - name: Generar reporte de cobertura
        run: npm run test:coverage

      - name: Subir reporte de cobertura
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage/